from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain.agents import create_agent
from langgraph.graph import StateGraph, START, END
from pydantic import BaseModel, Field
from langgraph.checkpoint.memory import InMemorySaver
from typing import Literal
from langchain_community.utilities import GoogleSerperAPIWrapper
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
import os

load_dotenv()

### Initialization Section

llm = ChatGroq(model = "openai/gpt-oss-20b")

class Response(BaseModel):
    query:str = Field(...,description= "Query field")
    context: str = Field(description= "Context of the Response", default ="")
    choice: Literal["Cricket", "Football", "Badminton"] = Field( description = "The choice of action to be taken by the agent.", default="Football")
    answer: str = Field(description="Answer from Node", default= "")
    human_feedback: str = Field(description = "Human Provided Feedback", default= "No")
    draft_email: str = Field(description = "AI Generated Draft Mail", default= "")
    final_response :str = Field(description = "Final Response Generated by AI", default= "")

class Choice(BaseModel):
      choice: Literal["Cricket", "Football", "Badminton"] = Field( description="The choice of action to be taken by the agent.", default="Football")

graph = StateGraph(Response)
search = GoogleSerperAPIWrapper()
tool = search.run
memory = InMemorySaver()
config = {"configurable" : {"thread_id":1}}
persistent_directory = '../db/chroma_db'

### Document Loading

document_path = os.path.normpath(os.path.join(os.path.dirname(__file__), "../files/pdf/Resume.pdf"))
loader = PyPDFLoader(document_path)
docs = loader.load()

### Document Spliting

splitter = RecursiveCharacterTextSplitter(chunk_size =10000, chunk_overlap =100)
splited_docs = splitter.split_documents(docs)

###  Vector Embeddings && Storing in Vector DB

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")

if os.path.exists(persistent_directory):
     vector_store = Chroma(
          embedding_function = embeddings,
          persist_directory= persistent_directory
     )
else:
     vector_store = Chroma.from_documents(
          documents = splited_docs,
          embedding = embeddings,
          persist_directory = persistent_directory
     )

### Helpers

def Create_Context(query:str, state:Response) -> str:
    search = vector_store.similarity_search(query)
    context = ""
    for chunk in search:
         context += chunk.page_content + "\n"
    state.context = context
    return context

def get_agent():
     agent = create_agent(
          model = llm,
          tools = [tool],
          system_prompt = " You are an smart Google Search Agent who always use Google Search to generate answer"
     )
     return agent


### Creation of Nodes

def Task_Identifier(state:Response) -> Response:
      str_llm = llm.with_structured_output(Choice)
      response = str_llm.invoke(f"""
                                Identify the Choice in User Question :{state.query}, using the 
                                context {Create_Context(state.query, state)}
                                """)
      state.choice = response.choice
      return state
        
def route( state: Response) -> Literal["Cricket", "Football", "Badminton"]:
    return state.choice

def Cricket(state:Response) -> Response:
     response = llm.invoke(state.query).content
     state.answer = response
     return state

def Football(state:Response) -> Response:
     response = get_agent().invoke(
          {"messages":[{"role":"user", "content": state.query}]
     })
     print(response)
     state.answer = response
     return state

def Badminton(state:Response) -> Response:
     response = llm.invoke(state.query).content
     state.answer = response
     return state

### Building Nodes

graph.add_node("identify_choice", Task_Identifier)
graph.add_node("Cricket", Cricket)
graph.add_node("Football", Football)
graph.add_node("Badminton", Badminton)

graph.add_edge(START, "identify_choice")
graph.add_conditional_edges("identify_choice", route)
graph.add_edge("Cricket", END)
graph.add_edge("Football", END)
graph.add_edge("Badminton", END)

graph = graph.compile()

response = graph.invoke({"role":"user", "query":"Identify the Sports of the Candidate Played and then Draft 10 questions regarding the sports"})
print(response)

from IPython.display import Image
Image(graph.get_graph().draw_mermaid_png())
